#!/usr/bin/python2
"""
Allows to load lastfm:// playlists in mpd
for usage just check the optionParser options

Feel free to redistribute
"""

from optparse import OptionParser
from time import sleep
import os
import mpd

mpd = mpd.MPDClient()


def add_to_mpd(type, station, count=1):
    for i in station.split(','):
        if type in ['artist', 'user', 'globaltags', 'genre']:
            print 'adding lastfm://' + type + '/' + i.replace(' ', '+')
            for _ in xrange(count):
                try:
                    mpd.load('lastfm://' + type + '/' + i.replace(' ', '+'))
                except:
                    pass
                sleep(1)
        elif type == "recommendations":
            print 'adding lastfm://user/' + i + '/recommendations'
            for _ in xrange(count):
                try:
                    mpd.load('lastfm://user/' + i + '/recommendations')
                except:
                    pass
                sleep(1)

if __name__ == "__main__":
    opts = OptionParser()
    opts.add_option("-a", "--artist", default=None,
                    help="Comma separated list of artists")
    opts.add_option("-u", "--user", default=None,
                    help="Comma separated list of users")
    opts.add_option("-t", "--globaltags", default=None,
                    help="Comma separated list of tags")
    opts.add_option("-r", "--recommendations", default=None,
                    help="Comma separated list of users")
    opts.add_option("-g", "--genre", default=None
                    help="Comma separated list of genres")
    opts.add_option("-c", "--count", default=1,
                    help="Number of times to add the lastfm:// url")
    (options, args) = opts.parse_args()

    host = os.getenv("MPD_HOST", "localhost")
    port = os.getenv("MPD_POT", 6600)

    mpd.connect(host, port)

    for values in vars(options).iteritems():
        if values[1] is not None:
            add_to_mpd(values[0], values[1], int(options.count))
