#!/usr/bin/python2
import os
import sys
try:
    import mpd
except ImportError:
    print "python-mpd module not found"
    print "It's available at:"
    print "http://jatreuman.indefero.net/p/python-mpd/"

try:
    import pynotify
except ImportError:
    print "python-notify module not found"

MAX_SUMMARY_LENGTH = 39

if os.fork() == 0:
    m = mpd.MPDClient()
    MPD_HOST = os.getenv("MPD_HOST","localhost")
    MPD_PORT = os.getenv("MPD_PORT",6600)
    m.connect(MPD_HOST, MPD_PORT)
    status = m.status()["state"]
    pynotify.init("MPD")

    while True:
        m.idle("player")
        tempstate = m.status()["state"]
        song = m.currentsong()

        for tag in ("album", "artist","title"):
            if not tag in song.keys():
                song[tag] = "Unknown %s" % tag

        if len(song["title"]) >= MAX_SUMMARY_LENGTH:
            song["title"] = "".join([song["title"][:MAX_SUMMARY_LENGTH-3],"..."])

        if tempstate == "play":
            n = pynotify.Notification(song["title"],
                    "by <b>%s</b>\non <b>%s</b>" % 
                    (song["artist"],
                     song["album"]),
                    "notification-audio-next")
            n.show()

        if "-s" in sys.argv:
            if tempstate != status:
                n = pynotify.Notification("MPD: %s" % tempstate,
                        "was: <b>%s</b>" % status,"notification-audio-%s" %
                        tempstate)
                n.show()
        status = tempstate
else:
    exit(0)
