#!/usr/bin/python2
"""
MPDT(hingie) allows you to love and tag tracks on last.fm via command line.
Options:
    -t, --titletag tag1:tag2:
        Tag the currently playing song in mpd with tag1, tag2 and so on.
        Tags are separated by colons, not spaces!
        "Awesome tag" is one(!) tag
    -a, --artisttag tag1:tag2:
        Same as -tt but for artists
    -l, --love
        Love the currently playing song in mpd
    -h, --help
        Show this message

You will need a config file in "$XDG_CONFIG_HOME/mpdt/config" with the
following content:
    api_key your_api_key
    api_secret your_api_secret
    username your_lastfm_username
    password your_lastfm_password_hash
        (generate it with "echo -n password|md5sum")
"""
import pylast
import os
import sys
import mpd

from common import connect_to_lastfm, connect_to_mpd
from optparse import OptionParser

def _unicode(text):
    if type(text) != unicode:
        return unicode(text, "utf-8")

if __name__ == "__main__":
    parser = OptionParser()
    parser.add_option("-l","--love",action="store_true")
    parser.add_option("-a","--artisttag",dest="artisttag")
    parser.add_option("-t","--titletag",dest="titletag")

    m = connect_to_mpd()
    song = m.currentsong()

    for key in ["artist", "title", "album"]:
        song[key] = _unicode(song[key])

    (options,args) = parser.parse_args()

    network = connect_to_lastfm()

    if options.love:
        try:
            track = network.get_track(song["artist"], song["title"])
            track.love()
            try:
                sys.argv.remove("-l")
                sys.argv.remove("--love")
            except ValueError:
                pass
        except KeyError:
            sys.exit("Songs tags are not correctly set")

    if options.titletag is not None:
        try:
            track = network.get_track(song["artist"], song["title"])
            track.add_tags(options.titletag.split(":"))
        except KeyError:
            sys.exit("Songs tags are not correctly set")

    if options.artisttag is not None:
        try:
            artist = network.get_artist(song["artist"])
            artist.add_tags(options.artisttag.split(":"))
        except KeyError:
            sys.exit("Song tags are not correctly set")
